controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    closed_loop_pos_controller:
      type: effort_controllers/JointPositionController
      joint: slider_to_cart
      pid: {p: 100.0, i: 0.00, d: 10}

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# closed_loop_position_controller:
#   ros__parameters:
#     joints:
#       - slider_to_cart
#     command_interfaces:
#       - effort
#     state_interfaces:
#       - position
#       - velocity
#       - effort
