controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    gripper_controller:
      type: effort_controllers/JointGroupEffortController

    base_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

gripper_controller:
  ros__parameters:
    joints:
      - right_finger_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort

base_controller:
  ros__parameters:
    joints:
      - base_prismatic
    interface_name: position
