controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    gripper_controller:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

gripper_controller:
  ros__parameters:
    joints:
      - right_finger_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort